export const TheaterLayout = {
    Seats: [
      { id: 0, name: "A1", available: false},
      { id: 1, name: "A2", available: false },
      { id: 2, name: "A3", available: true },
      { id: 3, name: "A4", available: true },
      { id: 4, name: "A5", available: true },
      { id: 5, name: "A6", available: true },
      { id: 6, name: "A7", available: true },
      { id: 7, name: "A8", available: true },
      { id: 8, name: "A9", available: true },
      { id: 9, name: "A10", available: true },
      { id: 10, name: "B1", available: true },
      { id: 11, name: "B2", available: true },
      { id: 12, name: "B3", available: true },
      { id: 13, name: "B4", available: true },
      { id: 14, name: "B5", available: true },
      { id: 15, name: "B6", available: true },
      { id: 16, name: "B7", available: false },
      { id: 17, name: "B8", available: false },
      { id: 18, name: "B9", available: false },
      { id: 19, name: "B10", available: false },
      { id: 20, name: "C1", available: true },
      { id: 21, name: "C2", available: true },
      { id: 22, name: "C3", available: true },
      { id: 23, name: "C4", available: true },
      { id: 24, name: "C5", available: true },
      { id: 25, name: "C6", available: true },
      { id: 26, name: "C7", available: true },
      { id: 27, name: "C8", available: true },
      { id: 28, name: "C9", available: true },
      { id: 29, name: "C10", available: true },
    ]
}; 