export const Movies = {
    Showing: [{
        id: 0,
        name: "Once Upon a Time in Hollywood",
        linkName: "OnceUponATimeInHollywood",
        image: 'https://imgc.allpostersimages.com/img/posters/once-upon-a-time-in-hollywood_u-L-F9JL6E0.jpg',
        trailer: 'https://www.youtube.com/embed/ELeMaP8EPAA',
        rating: "R",
        category: ['Comedy', 'Drama'],
        cast: 'Leonardo DiCaprio, Brad Pitt, Marogt Robbie, Kurt Russell',
        director: 'Quentin Tarantino',
        producer: 'David Heyman, Shannon McIntosh, Quentin Tarantino',
        description: 'Actor Rick Dalton gained fame and fortune by starring in a 1950s television Western, but is now struggling to find meaningful work in a Hollywood that he does not recognize anymore. He spends most of his time drinking and palling around with Cliff Booth, his easygoing best friend and longtime stunt double. Rick also happens to live next door to Roman Polanski and Sharon Tate, the filmmaker and budding actress whose futures will forever be altered by members of the Manson Family.',
        reviews: 'https://www.rottentomatoes.com/m/once_upon_a_time_in_hollywood/reviews?type=top_critics', 
        shown: true,
        showDate: ['02-22-2023', '03-01-2023'],
        showTime: ['3:30PM', '7:00PM'],
        rows: 20,
        cols: 6,
        seats: {
            A: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            B: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            C: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            D: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            E: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            F: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            G: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        }
    },
    {
        id: 1,
        name: 'Sonic The Hedgehog',
        linkName: 'SonicTheHedgehog',
        image: 'https://imgix.ranker.com/user_node_img/2082/41636634/original/sonic-the-hedgehog-photo-u5?auto=format&q=60&fit=crop&fm=pjpg&dpr=2&w=375',
        trailer: 'https://www.youtube.com/embed/DHR3aHwMe2g',
        rating: "PG",
        category: ['Kids and Family', 'Adventure', 'Comedy'] ,
        cast: 'James Marsden, Jim Carrey, Ben Schwartz, Tika Sumpter',
        director: 'Jeff Fowler',
        producer: 'Neal H. Moritz, Toby Ascher, Toru Nakahara, Takeshi Ito',
        description: 'The world needed a hero -- it got a hedgehog. Powered with incredible speed, Sonic embraces his new home on Earth -- until he accidentally knocks out the power grid, sparking the attention of uncool evil genius Dr. Robotnik. Now, it\'s supervillain vs. supersonic in an all-out race across the globe to stop Robotnik from using Sonic\'s unique power to achieve world domination.',
        reviews: 'https://www.rottentomatoes.com/m/sonic_the_hedgehog_2020/reviews?type=top_critics', 
        shown: true,
        showDate: ['02-22-2023', '02-28-2023'],
        showTime: ['1:00PM', '5:00PM'],
        rows: 20,
        cols: 6,
        seats: {
            A: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            B: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            C: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            D: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            E: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            F: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            G: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        }
    },
    {
        id: 2,
        name: 'Black Adam',
        linkName: 'BlackAdam',
        image: 'https://www.theilluminerdi.com/wp-content/uploads/2022/09/black-adam-heroes.jpg',
        trailer: 'https://www.youtube.com/embed/JaV7mmc9HGw',
        rating: "PG-13",
        category: ['Action', 'Fantasy'],
        cast: 'Dwayne Johnson, Aldis Hodge, Noah Centineo, Sarah Shahi',
        director: 'Jaume Collet-Serra',
        producer: 'Beau Flynn, Hiram Garcia, Dwayne Johnson, Dany Garcia',
        description: 'Nearly 5,000 years after he was bestowed with the almighty powers of the ancient gods--and imprisoned just as quickly--Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
        reviews: 'https://www.rottentomatoes.com/m/black_adam/reviews?type=top_critics',
        shown: true,
        showDate: ['02-28-2023', '03-01-2023'],
        showTime: ['4:00PM', '8:30PM'],
        rows: 20,
        cols: 6,
        seats: {
            A: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            B: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            C: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            D: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            E: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            F: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            G: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        }
    }],

    NotShowing: [{
        id: 0,
        name: 'Avatar: The Way of Water',
        linkName: 'AvatarTheWayOfWater',
        image: 'https://amc-theatres-res.cloudinary.com/image/upload/f_auto,fl_lossy,h_465,q_auto,w_310/v1667397461/amc-cdn/production/2/movies/53700/53699/PosterDynamic/145397.jpg',
        trailer: 'https://www.youtube.com/embed/d9MyW72ELq0',
        rating: "PG-13",
        category: ['Sci-fi', 'Action'],
        cast: 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang',
        director: 'James Cameron',
        producer: 'James Cameron, Jon Landau',
        description: 'Set more than a decade after the events of the first film, "Avatar: The Way of Water" begins to tell the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
        reviews: 'https://www.rottentomatoes.com/m/avatar_the_way_of_water/reviews?type=top_critics',
        shown: false,
        showDate: "",
        showTime: ""
    },
    {
        id: 1,
        name: 'Puss in Boots: The Last Wish',
        linkName: 'PussInBootsTheLastWish',
        image: 'https://upload.wikimedia.org/wikipedia/en/7/78/Puss_in_Boots_The_Last_Wish_poster.jpg',
        trailer: 'https://www.youtube.com/embed/tHb7WlgyaUc',
        rating: "PG",
        category: ['Adventure', 'Comedy', 'Kids and Family'],
        cast: 'Antonio Banderas, Salma Hayek, Olivia Colman, Harvey Guillen',
        director: 'Joel Crawford',
        producer: 'Mark Swift',
        description: 'Outlaw Puss in Boots discovers that his passion for peril and disregard for safety have taken their toll. Puss has burned through eight of his nine lives, though he lost count along the way. Getting those lives back will send Puss in Boots on his grandest quest yet.',
        reviews: 'https://www.rottentomatoes.com/m/puss_in_boots_the_last_wish/reviews?type=top_critics',
        shown: false,
        showDate: "",
        showTime: ""
    }]
};